# .github/workflows/your-file-name.yml

name: Scrape Talk Locations

on:
  push:
    paths:
      - 'talks/**'
      - 'talkmap.ipynb'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Updated to the latest, most secure version
    - name: Check out repository
      uses: actions/checkout@v4

    # Updated to the latest version and added caching
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        # Add caching to speed up future runs
        cache: 'pip'

    - name: Install dependencies
      run: |
        pip install jupyter pandas requests beautifulsoup4 geopy
        pip install getorg --upgrade

    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute talkmap.ipynb --output talkmap_out.ipynb

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        # This will commit only if there are changes. If not, it continues without error.
        git diff-index --quiet HEAD || git commit -m "Automated update of talk locations"
        git push